### ISSUE TITLE
FR: hotkey support

### ISSUE THREAD

**Issue by Liquidmantis** [wilkerlucio/media-looper#1]
I just found your extension and already think it's great.  I love that it supports multiple named persistent loops.

I've already got a few feature requests though:
Love to have:
- hotkey support (I'm setting up a MIDI foot controller (Nektar Pacer) right now with keyboard mappings and it would be great to control loops)
  - loop start
  - loop end
  - back to loop beginning
  - loop toggle

Nice to have:
- additional hotkey support
  - next loop
  - previous loop
  -  +/- speed
- export/import loops (for backup/transfer to a different machine)

**Comment by haleypearse** [comment]
Also love this, just discovered. Going to be awesome to learn Coltrane solos on the piano haha. Also would love hotkey support. Specifically I was very excited to read about holding shift, because I've long wanted to hold shift to limit the span of arrow key navigation, and I thought that was what this meant. So please consider making shift also have this effect on arrow key navigation, or perhaps a configurable amount of time.

**Comment by wilkerlucio** [comment]
Hello folks, the latest version covers some of these with the new `alt+z` shortcut, from the basics I'm only missing the toggle, I'll add it soon. You guys have suggestions for what you think would be a good shortcut for that one? I'm thinking alt+space for the loop toggle. I also think for that to work we need a notion of "selected loop", otherwise its unclear what to toggle when no loop is selected.

**Comment by wilkerlucio** [comment]
I'm closing this until we get more info.

**Comment by Liquidmantis** [comment]
Oh, nice!  I missed the updates on this issue and had found other solutions, but having persistent state is a huge plus so I'll have to give this another visit.  

Thanks for the work!
